POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Unite Summit",
  "details": "Um evento para quem é apaixonado por informação",
  "maximumAttendees": 100
}

###

POST http://localhost:3333/events/f8810714-408e-4df6-8983-ee987bccdd90/attendees
Content-Type: application/json

{ 
  "name": "Ana Julia",
  "email": "ana@gmail.com"
}

###

GET http://localhost:3333/events/f8810714-408e-4df6-8983-ee987bccdd90


###

GET http://localhost:3333/attendees/1/badge